[env:sparkfun_promicro16]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino

build_flags =
    -flto
    -mcall-prologues
    -fno-inline-small-functions
    -fno-split-wide-types
    -Wl,--relax

monitor_speed = 115200

lib_deps =
    fastled/FastLED
