[platformio]
default_envs = sparkfun_promicro16_bench

[env]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino

monitor_speed = 115200

lib_deps =
    fastled/FastLED

[env:sparkfun_promicro16_bench]
build_flags =
    -DPOWER_PROFILE_PSU=0

[env:sparkfun_promicro16_psu]
build_flags =
    -DPOWER_PROFILE_PSU=1
